using LokynexHealth.Application.Common.Interfaces;
using LokynexHealth.Application.Orders.Common;
using LokynexHealth.Domain.Entities;
using MediatR;

namespace LokynexHealth.Application.Orders.Commands.CreateOrder;

public class CreateOrderCommandHandler : IRequestHandler<CreateOrderCommand, Guid>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;

    public CreateOrderCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    {
        _db = db;
        _currentUser = currentUser;
    }

    public async Task<Guid> Handle(CreateOrderCommand request, CancellationToken ct)
    {
        var now = DateTimeOffset.UtcNow;
        var actor = await OrderActorResolver.ResolveAsync(_db, _currentUser, ct);

        var order = new Order
        {
            Id = Guid.NewGuid(),
            OrderNumber = null!,          // generated by the DB sequence
            CreatedBy = actor.UserId,     // null for the Lab Admin (FK safety)
            CreatedByName = actor.Name,
            CreatedAt = now
        };

        var composed = await OrderComposer.ApplyAsync(_db, request, order, now, ct);

        _db.Orders.Add(order);
        _db.OrderItems.AddRange(composed.Items);
        _db.OrderPayments.AddRange(composed.Payments);

        await _db.SaveChangesAsync(ct);
        return order.Id;
    }
}